name = "gwt"
version = "0.2.0"

description = "A JWT library written in Gleam"

licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = "~> 0.35.1"
gleam_json = "~> 1.0"
gleam_crypto = "~> 1.3"

[dev-dependencies]
gleeunit = "~> 1.0"
