name = "gwt"
version = "0.4.0"

description = "A JWT library written in Gleam"

licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_json = "~> 1.0"
gleam_crypto = "~> 1.3"
birl = "~> 1.5"

[dev-dependencies]
gleeunit = "~> 1.0"
