name = "gwt"
version = "2.0.0"
description = "A JWT library written in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "brettkolodny", repo = "gwt" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_json = "~> 2.0"
gleam_crypto = "~> 1.3"
birl = "~> 1.7"

[dev-dependencies]
gleeunit = "~> 1.0"
